spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/webtoon
    username: root
    password: 1234
    driverClassName: org.mariadb.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: create
  jwt:
    secret: emVyby1iYXNlLWh3LXRhYmxlaW5n
